Working on utility script stubs.

diff --git a/_stubs/mount-crypto b/_stubs/mount-crypto
--- a/_stubs/mount-crypto
+++ b/_stubs/mount-crypto
@@ -1,5 +1,81 @@
+#!/bin/bash 
+#DEV: the above line must be removed
 
 # ----------------------------------------------------------------------------
+
+# REOPEN:
+
+# sudo zpool import pool-${CRYPTOVAULTLABEL}
+# sudo zpool scrub pool-${CRYPTOVAULTLABEL}
+# -or-
+# sudo mount /dev/mapper/${CRYPTOVAULTLABEL} ${MOUNTPATH}
+
+# set up the loop device
+echo -e "\e${BIWhite}Setting up the loop device...\e${Color_Off}"
+if ! sudo -n true 2>/dev/null; then 
+  echo -e "\e${IYellow}This operation requires you to re-enter your sudo password below:\e${Color_Off}"
+fi
+loopdev=`sudo losetup -f`
+echo "Using loop device: $loopdev"
+executable="losetup $loopdev ${VAULTPATH}/${CRYPTOVAULTLABEL}"
+echo -e "${executing}$elevated: $executable"
+sudoit $executable
+# to confirm/test, pull label with $loopdev, compare to the label
+
+echo
+
+# open the mapped loop device (req. selected encryption password)
+echo -e "\e${BIWhite}Opening the mapped device...\e${Color_Off}"
+executable="cryptsetup luksOpen $loopdev ${CRYPTOVAULTLABEL}"
+echo -e "${executing}$elevated: $executable"
+echo -e "\e${IYellow}The encrypted device is being opened. Please enter below the encryption password\nyou selected earlier in the process (NOTE: typed characters will not echo).\e${Color_Off}"
+sudoit $executable
+
+echo
+
+# mounting the filesystem
+echo -e "\e${BIWhite}Mounting the ${CRYPTOFS} filesystem...\e${Color_Off}"
+if [ "$CRYPTOFS" = "zfs" ]; then
+  zpool_id="zpool-${CRYPTOVAULTLABEL}"
+  echo "zpool ID for this cryptodisk is: $zpool_id"
+  executable="zpool import $zpool_id"
+  echo -e "${executing}$elevated: $executable"  
+  sudoit $executable
+  echo "Currently mounted zfs filesystems:"
+  sudoit zfs list
+  echo -e "\e${BIWhite}Scrubbing the mounted filesystem (integrity check)...\e${Color_Off}"
+  executable="zpool scrub $zpool_id"
+  sudoit $executable  
+else
+  executable="mkfs.ext4 /dev/mapper/${CRYPTOVAULTLABEL}"
+  echo -e "${executing}$elevated: $executable"
+  sudoit $executable
+  executable_mount="mount /dev/mapper/${CRYPTOVAULTLABEL} ${MOUNTPATH}"
+  echo "Mounting ext4 filesystem..."
+  echo -e "${executing}$elevated: $executable_mount"
+  sudoit $executable_mount
+fi
+
+# test the mount
+mounttest=`mount | grep --color=never "$zpool_id"`
+if [ "${mounttest}" = "" ]; then
+  echo -e "\e${BWhite}\e${On_Red}Could not mount the crypt disk at  \"${MOUNTPATH}\". Unable to proceed.\e${Color_Off}"
+  cleanup
+fi
+
+if [ "$mountpath_owner" != "root" ]; then
+  echo
+  echo -e "\e${BIWhite}Setting the mountpoint permissions...\e${Color_Off}"
+  executable="chmod 770 ${MOUNTPATH}"
+  echo -e "${executing}$elevated: $executable"
+  sudoit $executable
+  executable="chown -R ${mountpath_owner} ${MOUNTPATH}"
+  echo -e "${executing}$elevated: $executable"
+  sudoit $executable
+fi
+
+
+### LEGACY BEGIN -------------------------------
  
 if [ ! -f ${CRYPT_DISK_FQFN} ]; then
   echo "Crypt disk '${CRYPT_DISK_FQFN}' missing. Cannot continue."
diff --git a/_stubs/umount-crypto b/_stubs/umount-crypto
--- a/_stubs/umount-crypto
+++ b/_stubs/umount-crypto
@@ -1,6 +1,88 @@
+#!/bin/bash 
+#DEV: the above line must be removed
 
 # ----------------------------------------------------------------------------
- 
+
+# CLOSE:
+
+# zfs:
+# sudo zpool export pool-${CRYPTOVAULTLABEL}
+# ext4:
+# umount ${MOUNTPATH} > /dev/null 2>&1
+
+#TODO: Add here a list of processes that hold the lock
+
+# sudo cryptsetup luksClose /dev/mapper/${CRYPTOVAULTLABEL}
+
+# DNAM=${CRYPTOVAULTLABEL}; LDEV=`sudo losetup --raw | grep $DNAM | awk '{print $1}'`; sudo losetup -d $LDEV
+
+  # export zfs pool, umount ext4 fs
+  dismounted="false"
+  if [ "$CRYPTOFS" = "zfs" ]; then
+
+    #export zfs
+    while [ "$dismounted" = "false" ]; do
+      sudoit zpool export $zpool_id
+      if [ $? -ne 0 ]; then
+        echo "Unable to unmount the disk; device is busy. Free the device and try again."
+        echo "The following process(es) hold the mount:"
+        x=(); for a in $(mount | cut -d' ' -f3); do test -e "$a" || x+=("-e$a"); done
+        lsof "${x[@]}" -f -- ${MOUNTPATH}
+        echo
+        read -p "Press any key to retry unmount! " -n1 -s
+      else
+        dismounted="true"
+      fi
+    done
+    echo "zfs pool exported."
+
+  else
+  
+    # unmount ext4
+    while [ "$dismounted" = "false" ]; do
+      sudoit umount ${MOUNTPATH}
+      if [ $? -ne 0 ]; then
+          echo "Unable to unmount the disk; device is busy. Free the device and try again."
+          echo "The following process(es) hold the mount:"
+          x=(); for a in $(mount | cut -d' ' -f3); do test -e "$a" || x+=("-e$a"); done
+          lsof "${x[@]}" -f -- ${MOUNTPATH}
+          echo
+          read -p "Press any key to retry unmount! " -n1 -s
+      else
+        dismounted="true"
+      fi
+    done
+    echo "ext4 filesystem unmounted at ${MOUNTPATH}."
+    
+  fi  
+
+  # remove mapped disk
+  if [ -b /dev/mapper/${CRYPTOVAULTLABEL} ]; then
+    sudoit cryptsetup luksClose /dev/mapper/${CRYPTOVAULTLABEL}
+    echo "Mapped device /dev/mapper/${CRYPTOVAULTLABEL} removed."
+  fi
+
+  if ! sudo -n true 2>/dev/null; then 
+    echo -e "\e${IYellow}This operation requires you to re-enter your sudo password below:\e${Color_Off}"
+  fi 
+  # acquire loop device
+  loopdev2del=`sudo losetup --raw | grep ${VAULTPATH}/${CRYPTOVAULTLABEL} | awk '{print $1}'`
+  # delete loop device
+  if [ "$loopdev2del" != "" ]; then
+    sudoit losetup -d $loopdev2del > /dev/null 2>&1
+    echo "Loop device $loopdev2del removed."
+  fi
+  echo "Exiting.."
+  echo
+  exit 1
+
+
+
+
+
+
+### ---------- LEGACY BEGIN
+
 LOOPBACK_DEVICE=`losetup -j ${CRYPT_DISK} | awk '{print $1}' | sed '$s/.$//'`
  
 CAN_RELEASE=true
